### ISSUE TITLE
Tag release for packaging

### ISSUE THREAD

**Issue by wezm** [grapegrip/asd#3]
This looks like a really useful tool. I was looking for something like this just yesterday while writing out a long issue for work. I'd like to create an [AUR](https://aur.archlinux.org/) package for it. It's best to build OS packages like this from downloadable archives (such as as `tar` archive) so that the source code can be checked against a hash digest like SHA256. Would it be possible to create a git tag for releases? GitHub will then make tarballs available for each tagged release at: https://github.com/grapegrip/asd/releases which I can use to build the package.

**Comment by grapegrip** [comment]
So cool. I created a git tag for the first release!

**Comment by wezm** [comment]
Awesome! Package added: https://aur.archlinux.org/packages/asd/
